import { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import inquirer from 'inquirer';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { log } from '../utils/logger';
import { getProjectRoot, getMonitoringComposePath } from '../utils/paths';
import { getDockerComposeCommand } from '../utils/helpers';

function readEnv(envPath: string): Record<string, string> {
  const env: Record<string, string> = {};
  if (!fs.existsSync(envPath)) return env;
  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx > 0) {
      env[trimmed.substring(0, eqIdx).trim()] = trimmed.substring(eqIdx + 1).trim();
    }
  }
  return env;
}

function writeEnv(envPath: string, env: Record<string, string>) {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(env)) {
    lines.push(`${key}=${value}`);
  }
  fs.writeFileSync(envPath, lines.join('\n') + '\n');
}

function generateMonitoringCompose(services: Set<string>, env: Record<string, string>): string {
  const serviceSet = services;

  let compose = `# OpenFactu Monitoring Stack
# Generated by @openfactu/cli
# Services: ${Array.from(serviceSet).join(', ')}

services:
`;

  if (serviceSet.has('pgadmin')) {
    compose += `
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: openfactu-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: \${PGADMIN_EMAIL:-admin@openfactu.local}
      PGADMIN_DEFAULT_PASSWORD: \${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "\${PGADMIN_PORT:-5050}:80"
    volumes:
      - ./storage/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('prometheus')) {
    compose += `
  prometheus:
    image: prom/prometheus:latest
    container_name: openfactu-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - "\${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./storage/prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('grafana')) {
    compose += `
  grafana:
    image: grafana/grafana:latest
    container_name: openfactu-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=\${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=\${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - "\${GRAFANA_PORT:-3001}:3000"
    volumes:
      - ./storage/grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('loki')) {
    compose += `
  loki:
    image: grafana/loki:latest
    container_name: openfactu-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "\${LOKI_PORT:-3100}:3100"
    volumes:
      - ./storage/loki_data:/loki
      - ./monitoring/loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('promtail')) {
    compose += `
  promtail:
    image: grafana/promtail:latest
    container_name: openfactu-promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./monitoring/promtail/promtail-config.yaml:/etc/promtail/config.yml:ro
      - /var/log:/var/log
      - ./storage:/app/storage:ro
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('cadvisor')) {
    compose += `
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: openfactu-cadvisor
    ports:
      - "\${CADVISOR_PORT:-8081}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('node-exporter')) {
    compose += `
  node-exporter:
    image: prom/node-exporter:latest
    container_name: openfactu-node-exporter
    command:
      - '--path.rootfs=/host'
    ports:
      - "\${NODE_EXPORTER_PORT:-9100}:9100"
    volumes:
      - /:/host:ro,rslave
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('portainer')) {
    compose += `
  portainer:
    image: portainer/portainer-ce:latest
    container_name: openfactu-portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "\${PORTAINER_PORT:-9000}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./storage/portainer_data:/data
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('alertmanager')) {
    compose += `
  alertmanager:
    image: prom/alertmanager:latest
    container_name: openfactu-alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "\${ALERTMANAGER_PORT:-9093}:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./storage/alertmanager_data:/alertmanager
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  compose += `
networks:
  openfactu_net:
    name: openfactu_net
    driver: bridge
`;

  return compose;
}

function generatePrometheusConfig(): string {
  return `global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'openfactu-server'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['server:3000']
`;
}

function generateLokiConfig(): string {
  return `auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
`;
}

function generatePromtailConfig(): string {
  return `server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: openfactu-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: openfactu
          __path__: /app/storage/**/*.log
`;
}

export function registerMonitoringCommand(program: Command) {
  // ── openfactu monitoring ──
  program
    .command('monitoring')
    .description('Configura el stack de monitoreo y analitica')
    .option('--generate-compose', 'Generar docker-compose.monitoring.yml')
    .option('--with-analytics', 'Incluir stack completo de analitica')
    .action(async (opts) => {
      console.log();
      console.log(chalk.bold.white('  OpenFactu — Configurar Monitoreo'));
      console.log(chalk.dim('  ────────────────────────────────────'));
      console.log();

      try {
        const root = getProjectRoot();
        const envPath = path.join(root, '.env');
        const env = readEnv(envPath);

        const includeAnalytics = opts.withAnalytics || false;

        const { services } = await inquirer.prompt([
          {
            type: 'checkbox',
            name: 'services',
            message: 'Servicios a activar:',
            choices: [
              { name: 'pgAdmin (gestion BD)', value: 'pgadmin', checked: true },
              { name: 'Grafana (dashboards)', value: 'grafana', checked: true },
              { name: 'Prometheus (metricas)', value: 'prometheus', checked: true },
              { name: 'Loki (agregacion de logs)', value: 'loki', checked: includeAnalytics },
              { name: 'Promtail (envio de logs a Loki)', value: 'promtail', checked: includeAnalytics },
              { name: 'cAdvisor (metricas contenedores)', value: 'cadvisor', checked: includeAnalytics },
              { name: 'Node Exporter (metricas host)', value: 'node-exporter', checked: includeAnalytics },
              { name: 'Portainer (gestion Docker)', value: 'portainer', checked: true },
              { name: 'Alertmanager (alertas)', value: 'alertmanager', checked: false },
            ],
          },
        ]);

        const serviceSet = new Set<string>(services as string[]);

        const { customizePorts } = await inquirer.prompt([
          {
            type: 'confirm',
            name: 'customizePorts',
            message: 'Personalizar puertos?',
            default: false,
          },
        ]);

        const ports: Record<string, string> = {};
        if (customizePorts) {
          const portQuestions = [];
          if (serviceSet.has('pgadmin')) portQuestions.push({ type: 'input', name: 'PGADMIN_PORT', message: 'Puerto pgAdmin:', default: env.PGADMIN_PORT || '5050' });
          if (serviceSet.has('grafana')) portQuestions.push({ type: 'input', name: 'GRAFANA_PORT', message: 'Puerto Grafana:', default: env.GRAFANA_PORT || '3001' });
          if (serviceSet.has('prometheus')) portQuestions.push({ type: 'input', name: 'PROMETHEUS_PORT', message: 'Puerto Prometheus:', default: env.PROMETHEUS_PORT || '9090' });
          if (serviceSet.has('loki')) portQuestions.push({ type: 'input', name: 'LOKI_PORT', message: 'Puerto Loki:', default: env.LOKI_PORT || '3100' });
          if (serviceSet.has('cadvisor')) portQuestions.push({ type: 'input', name: 'CADVISOR_PORT', message: 'Puerto cAdvisor:', default: env.CADVISOR_PORT || '8081' });
          if (serviceSet.has('node-exporter')) portQuestions.push({ type: 'input', name: 'NODE_EXPORTER_PORT', message: 'Puerto Node Exporter:', default: env.NODE_EXPORTER_PORT || '9100' });
          if (serviceSet.has('portainer')) portQuestions.push({ type: 'input', name: 'PORTAINER_PORT', message: 'Puerto Portainer:', default: env.PORTAINER_PORT || '9000' });
          if (serviceSet.has('alertmanager')) portQuestions.push({ type: 'input', name: 'ALERTMANAGER_PORT', message: 'Puerto Alertmanager:', default: env.ALERTMANAGER_PORT || '9093' });

          if (portQuestions.length > 0) {
            const answers = await inquirer.prompt(portQuestions);
            Object.assign(ports, answers);
          }
        }

        const { customizeCredentials } = await inquirer.prompt([
          {
            type: 'confirm',
            name: 'customizeCredentials',
            message: 'Personalizar credenciales?',
            default: false,
          },
        ]);

        if (customizeCredentials) {
          if (serviceSet.has('pgadmin')) {
            const creds = await inquirer.prompt([
              { type: 'input', name: 'PGADMIN_EMAIL', message: 'Email pgAdmin:', default: env.PGADMIN_EMAIL || 'admin@openfactu.local' },
              { type: 'password', name: 'PGADMIN_PASSWORD', message: 'Password pgAdmin:', default: env.PGADMIN_PASSWORD || 'admin' },
            ]);
            Object.assign(ports, creds);
          }
          if (serviceSet.has('grafana')) {
            const creds = await inquirer.prompt([
              { type: 'input', name: 'GRAFANA_USER', message: 'Usuario Grafana:', default: env.GRAFANA_USER || 'admin' },
              { type: 'password', name: 'GRAFANA_PASSWORD', message: 'Password Grafana:', default: env.GRAFANA_PASSWORD || 'admin' },
            ]);
            Object.assign(ports, creds);
          }
        }

        // Generate compose file
        if (opts.generateCompose) {
          const composeSpinner = ora('Generando docker-compose.monitoring.yml...').start();
          const composeContent = generateMonitoringCompose(serviceSet, env);
          const composePath = path.join(root, 'docker-compose.monitoring.yml');
          fs.writeFileSync(composePath, composeContent);
          composeSpinner.succeed('docker-compose.monitoring.yml generado');

          // Generate config files
          if (serviceSet.has('prometheus')) {
            const promDir = path.join(root, 'monitoring/prometheus');
            fs.mkdirSync(promDir, { recursive: true });
            fs.writeFileSync(path.join(promDir, 'prometheus.yml'), generatePrometheusConfig());
          }

          if (serviceSet.has('loki')) {
            const lokiDir = path.join(root, 'monitoring/loki');
            fs.mkdirSync(lokiDir, { recursive: true });
            fs.writeFileSync(path.join(lokiDir, 'loki-config.yaml'), generateLokiConfig());
          }

          if (serviceSet.has('promtail')) {
            const promtailDir = path.join(root, 'monitoring/promtail');
            fs.mkdirSync(promtailDir, { recursive: true });
            fs.writeFileSync(path.join(promtailDir, 'promtail-config.yaml'), generatePromtailConfig());
          }
        }

        // Save config
        const envSpinner = ora('Guardando configuracion...').start();
        for (const [key, value] of Object.entries(ports)) {
          env[key] = value;
        }
        env.MONITORING_SERVICES = services.join(',');
        writeEnv(envPath, env);
        envSpinner.succeed('Configuracion guardada en .env');

        log.blank();
        const { start } = await inquirer.prompt([
          {
            type: 'confirm',
            name: 'start',
            message: 'Levantar los servicios de monitoreo ahora?',
            default: true,
          },
        ]);

        if (start) {
          const dockerCmd = getDockerComposeCommand();
          const composePath = path.join(root, 'docker-compose.monitoring.yml');

          if (!fs.existsSync(composePath)) {
            log.warn('docker-compose.monitoring.yml no existe');
            log.dim('  Ejecuta: openfactu monitoring --generate-compose');
            return;
          }

          const upSpinner = ora('Levantando servicios...').start();
          try {
            const scaleFlags = [];
            const allServices = ['pgadmin', 'grafana', 'prometheus', 'loki', 'promtail', 'cadvisor', 'node-exporter', 'portainer', 'alertmanager'];
            for (const svc of allServices) {
              scaleFlags.push(`--scale ${svc}=${serviceSet.has(svc) ? 1 : 0}`);
            }
            execSync(
              `${dockerCmd} -f docker-compose.monitoring.yml up -d ${scaleFlags.join(' ')}`,
              { cwd: root, stdio: 'pipe', timeout: 120000 },
            );
            upSpinner.succeed('Servicios levantados');
          } catch (err: any) {
            upSpinner.fail('Error: ' + err.message);
          }
        }

        log.blank();
        console.log(chalk.bold.green('  Monitoreo configurado'));
        console.log(chalk.dim('  ────────────────────────────────────'));
        log.blank();

        const urls: [string, string][] = [];
        if (serviceSet.has('pgadmin')) urls.push(['pgAdmin', `http://localhost:${env.PGADMIN_PORT || '5050'}`]);
        if (serviceSet.has('grafana')) urls.push(['Grafana', `http://localhost:${env.GRAFANA_PORT || '3001'}`]);
        if (serviceSet.has('prometheus')) urls.push(['Prometheus', `http://localhost:${env.PROMETHEUS_PORT || '9090'}`]);
        if (serviceSet.has('loki')) urls.push(['Loki', `http://localhost:${env.LOKI_PORT || '3100'}`]);
        if (serviceSet.has('cadvisor')) urls.push(['cAdvisor', `http://localhost:${env.CADVISOR_PORT || '8081'}`]);
        if (serviceSet.has('node-exporter')) urls.push(['Node Exporter', `http://localhost:${env.NODE_EXPORTER_PORT || '9100'}`]);
        if (serviceSet.has('portainer')) urls.push(['Portainer', `http://localhost:${env.PORTAINER_PORT || '9000'}`]);
        if (serviceSet.has('alertmanager')) urls.push(['Alertmanager', `http://localhost:${env.ALERTMANAGER_PORT || '9093'}`]);

        for (const [name, url] of urls) {
          log.info(`${chalk.dim(name.padEnd(15))} ${chalk.cyan(url)}`);
        }

        log.blank();
      } catch (err: any) {
        log.error(err.message);
        process.exitCode = 1;
      }
    });

  // ── openfactu monitoring:up ──
  program
    .command('monitoring:up')
    .description('Levanta los servicios de monitoreo')
    .action(async () => {
      try {
        const root = getProjectRoot();
        const dockerCmd = getDockerComposeCommand();
        const composeFile = path.join(root, 'docker-compose.monitoring.yml');

        if (!fs.existsSync(composeFile)) {
          log.error('docker-compose.monitoring.yml no encontrado');
          log.dim('  Ejecuta: openfactu monitoring --generate-compose');
          return;
        }

        const envPath = path.join(root, '.env');
        const env = readEnv(envPath);
        const services = (env.MONITORING_SERVICES || 'pgadmin,grafana,prometheus,loki,portainer').split(',');
        const serviceSet = new Set<string>(services as string[]);

        const spinner = ora('Levantando servicios...').start();
        const scaleFlags = [];
        const allServices = ['pgadmin', 'grafana', 'prometheus', 'loki', 'promtail', 'cadvisor', 'node-exporter', 'portainer', 'alertmanager'];
        for (const svc of allServices) {
          scaleFlags.push(`--scale ${svc}=${serviceSet.has(svc) ? 1 : 0}`);
        }
        execSync(
          `${dockerCmd} -f docker-compose.monitoring.yml up -d ${scaleFlags.join(' ')}`,
          { cwd: root, stdio: 'pipe', timeout: 120000 },
        );
        spinner.succeed('Servicios levantados');
      } catch (err: any) {
        log.error(err.message);
      }
    });

  // ── openfactu monitoring:down ──
  program
    .command('monitoring:down')
    .description('Para los servicios de monitoreo')
    .action(async () => {
      try {
        const root = getProjectRoot();
        const dockerCmd = getDockerComposeCommand();

        const spinner = ora('Parando servicios...').start();
        execSync(`${dockerCmd} -f docker-compose.monitoring.yml down`, { cwd: root, stdio: 'pipe' });
        spinner.succeed('Servicios parados');
      } catch (err: any) {
        log.error(err.message);
      }
    });

  // ── openfactu monitoring:status ──
  program
    .command('monitoring:status')
    .description('Estado de los servicios de monitoreo')
    .action(async () => {
      try {
        const root = getProjectRoot();
        const dockerCmd = getDockerComposeCommand();

        const output = execSync(`${dockerCmd} -f docker-compose.monitoring.yml ps`, { cwd: root }).toString();
        console.log(output);

        const envPath = path.join(root, '.env');
        const env = readEnv(envPath);
        log.blank();
        if (env.PGADMIN_PORT) log.info(`pgAdmin:    http://localhost:${env.PGADMIN_PORT}`);
        if (env.GRAFANA_PORT) log.info(`Grafana:    http://localhost:${env.GRAFANA_PORT}`);
        if (env.PROMETHEUS_PORT) log.info(`Prometheus: http://localhost:${env.PROMETHEUS_PORT}`);
        if (env.LOKI_PORT) log.info(`Loki:       http://localhost:${env.LOKI_PORT}`);
        if (env.CADVISOR_PORT) log.info(`cAdvisor:   http://localhost:${env.CADVISOR_PORT}`);
        if (env.NODE_EXPORTER_PORT) log.info(`Node Exp:   http://localhost:${env.NODE_EXPORTER_PORT}`);
        if (env.PORTAINER_PORT) log.info(`Portainer:  http://localhost:${env.PORTAINER_PORT}`);
      } catch (err: any) {
        log.error('Servicios no disponibles');
        log.dim('  ' + err.message);
      }
    });

  // ── openfactu monitoring:config ──
  program
    .command('monitoring:config')
    .description('Cambiar configuracion del monitoreo')
    .action(async () => {
      try {
        const root = getProjectRoot();
        const envPath = path.join(root, '.env');
        const env = readEnv(envPath);

        const { key } = await inquirer.prompt([
          {
            type: 'list',
            name: 'key',
            message: 'Variable a cambiar:',
            choices: [
              { name: `PGADMIN_PORT (${env.PGADMIN_PORT || '5050'})`, value: 'PGADMIN_PORT' },
              { name: `GRAFANA_PORT (${env.GRAFANA_PORT || '3001'})`, value: 'GRAFANA_PORT' },
              { name: `PROMETHEUS_PORT (${env.PROMETHEUS_PORT || '9090'})`, value: 'PROMETHEUS_PORT' },
              { name: `LOKI_PORT (${env.LOKI_PORT || '3100'})`, value: 'LOKI_PORT' },
              { name: `CADVISOR_PORT (${env.CADVISOR_PORT || '8081'})`, value: 'CADVISOR_PORT' },
              { name: `NODE_EXPORTER_PORT (${env.NODE_EXPORTER_PORT || '9100'})`, value: 'NODE_EXPORTER_PORT' },
              { name: `PORTAINER_PORT (${env.PORTAINER_PORT || '9000'})`, value: 'PORTAINER_PORT' },
              { name: `PGADMIN_EMAIL (${env.PGADMIN_EMAIL || 'admin@openfactu.local'})`, value: 'PGADMIN_EMAIL' },
              { name: `GRAFANA_USER (${env.GRAFANA_USER || 'admin'})`, value: 'GRAFANA_USER' },
            ],
          },
        ]);

        const { value } = await inquirer.prompt([
          { type: 'input', name: 'value', message: `Nuevo valor para ${key}:`, default: env[key] },
        ]);

        env[key] = value;
        writeEnv(envPath, env);
        log.success(`${key} actualizado a: ${value}`);
        log.info('Reinicia con: openfactu monitoring:down && openfactu monitoring:up');
      } catch (err: any) {
        log.error(err.message);
      }
    });

  // ── openfactu monitoring:generate ──
  program
    .command('monitoring:generate')
    .description('Generar docker-compose.monitoring.yml sin interaccion')
    .option('--services <services>', 'Servicios separados por coma')
    .option('--analytics', 'Incluir stack completo de analitica')
    .action(async (opts) => {
      try {
        const root = getProjectRoot();
        const envPath = path.join(root, '.env');
        const env = readEnv(envPath);

        let services: string[];
        if (opts.services) {
          services = opts.services.split(',');
        } else if (opts.analytics) {
          services = ['pgadmin', 'grafana', 'prometheus', 'loki', 'promtail', 'cadvisor', 'node-exporter', 'portainer'];
        } else {
          services = ['pgadmin', 'grafana', 'prometheus', 'portainer'];
        }

        const serviceSet = new Set<string>(services as string[]);
        const composeContent = generateMonitoringCompose(serviceSet, env);
        const composePath = path.join(root, 'docker-compose.monitoring.yml');
        fs.writeFileSync(composePath, composeContent);

        log.success('docker-compose.monitoring.yml generado');

        if (serviceSet.has('prometheus')) {
          const promDir = path.join(root, 'monitoring/prometheus');
          fs.mkdirSync(promDir, { recursive: true });
          fs.writeFileSync(path.join(promDir, 'prometheus.yml'), generatePrometheusConfig());
        }

        if (serviceSet.has('loki')) {
          const lokiDir = path.join(root, 'monitoring/loki');
          fs.mkdirSync(lokiDir, { recursive: true });
          fs.writeFileSync(path.join(lokiDir, 'loki-config.yaml'), generateLokiConfig());
        }

        if (serviceSet.has('promtail')) {
          const promtailDir = path.join(root, 'monitoring/promtail');
          fs.mkdirSync(promtailDir, { recursive: true });
          fs.writeFileSync(path.join(promtailDir, 'promtail-config.yaml'), generatePromtailConfig());
        }

        env.MONITORING_SERVICES = services.join(',');
        writeEnv(envPath, env);
      } catch (err: any) {
        log.error(err.message);
      }
    });
}
