import fs from 'fs';
import path from 'path';

/**
 * Catálogo de servicios de monitoreo. Fuente única usada tanto por el comando
 * `monitoring` como por `install` para construir el checkbox de selección.
 */
export interface MonitoringService {
  value: string;
  label: string;
  /** Marcado por defecto en un stack básico. */
  basic: boolean;
  /** Pertenece al stack de analítica avanzada (logs/métricas extendidas). */
  analytics: boolean;
}

export const MONITORING_CATALOG: MonitoringService[] = [
  { value: 'pgadmin', label: 'pgAdmin (gestion BD)', basic: true, analytics: false },
  { value: 'grafana', label: 'Grafana (dashboards)', basic: true, analytics: false },
  { value: 'prometheus', label: 'Prometheus (metricas)', basic: true, analytics: false },
  { value: 'loki', label: 'Loki (agregacion de logs)', basic: false, analytics: true },
  { value: 'promtail', label: 'Promtail (envio de logs a Loki)', basic: false, analytics: true },
  { value: 'cadvisor', label: 'cAdvisor (metricas contenedores)', basic: false, analytics: true },
  { value: 'node-exporter', label: 'Node Exporter (metricas host)', basic: false, analytics: true },
  { value: 'portainer', label: 'Portainer (gestion Docker)', basic: true, analytics: false },
  { value: 'alertmanager', label: 'Alertmanager (alertas)', basic: false, analytics: false },
];

export const ALL_MONITORING_SERVICES = MONITORING_CATALOG.map((s) => s.value);

/** Opciones para un prompt tipo checkbox de inquirer. */
export function monitoringChoices(opts: { analytics?: boolean } = {}) {
  return MONITORING_CATALOG.map((s) => ({
    name: s.label,
    value: s.value,
    checked: s.basic || (opts.analytics ? s.analytics : false),
  }));
}

/** Conjunto básico (pgAdmin, Grafana, Prometheus, Portainer). */
export function basicMonitoringServices(): string[] {
  return MONITORING_CATALOG.filter((s) => s.basic).map((s) => s.value);
}

/** Conjunto completo (básico + analítica). */
export function fullMonitoringServices(): string[] {
  return MONITORING_CATALOG.filter((s) => s.basic || s.analytics).map((s) => s.value);
}

/**
 * Renderiza un bloque `depends_on:` con solo las dependencias que están en el
 * conjunto seleccionado (evita "depends on undefined service" cuando se elige
 * un subconjunto). Devuelve '' si no queda ninguna dependencia presente.
 */
function dependsOn(serviceSet: Set<string>, deps: string[]): string {
  const present = deps.filter((d) => serviceSet.has(d));
  if (present.length === 0) return '';
  return `    depends_on:\n` + present.map((d) => `      - ${d}`).join('\n') + '\n';
}

/** Genera el docker-compose.monitoring.yml con solo los servicios seleccionados. */
export function generateMonitoringCompose(serviceSet: Set<string>): string {
  let compose = `# OpenFactu Monitoring Stack
# Generated by @openfactu/cli
# Services: ${Array.from(serviceSet).join(', ')}

services:
`;

  if (serviceSet.has('pgadmin')) {
    compose += `
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: openfactu-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: \${PGADMIN_EMAIL:-admin@openfactu.local}
      PGADMIN_DEFAULT_PASSWORD: \${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "\${PGADMIN_PORT:-5050}:80"
    volumes:
      - ./storage/pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('prometheus')) {
    compose += `
  prometheus:
    image: prom/prometheus:latest
    container_name: openfactu-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    ports:
      - "\${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./storage/prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('grafana')) {
    compose += `
  grafana:
    image: grafana/grafana:latest
    container_name: openfactu-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=\${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=\${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - "\${GRAFANA_PORT:-3001}:3000"
    volumes:
      - ./storage/grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
${dependsOn(serviceSet, ['prometheus', 'loki'])}    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('loki')) {
    compose += `
  loki:
    image: grafana/loki:latest
    container_name: openfactu-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "\${LOKI_PORT:-3100}:3100"
    volumes:
      - ./storage/loki_data:/loki
      - ./monitoring/loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('promtail')) {
    compose += `
  promtail:
    image: grafana/promtail:latest
    container_name: openfactu-promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./monitoring/promtail/promtail-config.yaml:/etc/promtail/config.yml:ro
      - /var/log:/var/log
      - ./storage:/app/storage:ro
${dependsOn(serviceSet, ['loki'])}    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('cadvisor')) {
    compose += `
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: openfactu-cadvisor
    ports:
      - "\${CADVISOR_PORT:-8081}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('node-exporter')) {
    compose += `
  node-exporter:
    image: prom/node-exporter:latest
    container_name: openfactu-node-exporter
    command:
      - '--path.rootfs=/host'
    ports:
      - "\${NODE_EXPORTER_PORT:-9100}:9100"
    volumes:
      - /:/host:ro,rslave
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('portainer')) {
    compose += `
  portainer:
    image: portainer/portainer-ce:latest
    container_name: openfactu-portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "\${PORTAINER_PORT:-9000}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./storage/portainer_data:/data
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  if (serviceSet.has('alertmanager')) {
    compose += `
  alertmanager:
    image: prom/alertmanager:latest
    container_name: openfactu-alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "\${ALERTMANAGER_PORT:-9093}:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./storage/alertmanager_data:/alertmanager
    restart: unless-stopped
    networks:
      - openfactu_net
`;
  }

  compose += `
networks:
  openfactu_net:
    name: openfactu_net
    driver: bridge
`;

  return compose;
}

export function generatePrometheusConfig(): string {
  return `global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'openfactu-server'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['server:3000']
`;
}

export function generateLokiConfig(): string {
  return `auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
`;
}

export function generatePromtailConfig(): string {
  return `server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: openfactu-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: openfactu
          __path__: /app/storage/**/*.log
`;
}

export function generateAlertmanagerConfig(): string {
  return `route:
  receiver: 'default'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'default'
`;
}

/**
 * Escribe los archivos de configuración necesarios para los servicios
 * seleccionados. Cada servicio que monta un archivo de config debe generarlo
 * aquí; si no, Docker crea un directorio en su lugar y el bind-mount falla.
 */
export function writeMonitoringConfigs(root: string, serviceSet: Set<string>): void {
  if (serviceSet.has('prometheus')) {
    const dir = path.join(root, 'monitoring/prometheus');
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'prometheus.yml'), generatePrometheusConfig());
  }
  if (serviceSet.has('loki')) {
    const dir = path.join(root, 'monitoring/loki');
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'loki-config.yaml'), generateLokiConfig());
  }
  if (serviceSet.has('promtail')) {
    const dir = path.join(root, 'monitoring/promtail');
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'promtail-config.yaml'), generatePromtailConfig());
  }
  if (serviceSet.has('alertmanager')) {
    const dir = path.join(root, 'monitoring/alertmanager');
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'alertmanager.yml'), generateAlertmanagerConfig());
  }
  if (serviceSet.has('grafana')) {
    // El servicio monta ./monitoring/grafana/provisioning (directorio :ro).
    // Lo creamos vacío para que el mount tenga una fuente real.
    fs.mkdirSync(path.join(root, 'monitoring/grafana/provisioning'), { recursive: true });
  }
}
